### PR TITLE
New Wiki! 

### PR DESCRIPTION
**Pull request by audreykoz**
Hey Herve, 
I've created a wiki for this plugin and added some new pictures and info to it while removing some of the content from the README. Same deal with the form plugin, the wiki is stored as a submodule. If that becomes an issue, just let me know and I can send you the files separately.

### CODE REVIEW

**Comment by herve91** [comment]
Thanks's very much Audrey :)

**Comment by herve91** [comment]
Hi Audrey,

I'm sorry, I merged your pull request but the wiki is still not created. Did I do something wrong ?

Thanks and regards
Hervé

**Comment by audreykoz** [comment]
Hmm weirdness, I think it has something to do with the wiki being a submodule. Let me just send you a folder with all the wiki files

**Comment by audreykoz** [comment]
[specialization-plugin.wiki.zip](https://github.com/archi-contribs/specialization-plugin/files/3351599/specialization-plugin.wiki.zip)

**Comment by herve91** [comment]
Thank you very much :)

**Pull request merged**
